// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _5544___Group_4_TALLER.Migrations
{
    [DbContext(typeof(DbGrupo4))]
    [Migration("20250501025443_Migracion de Datos")]
    partial class MigraciondeDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_5544___Group_4_TALLER.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Presupuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EquipoID");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("_5544___Group_4_TALLER.Models.Jugador", b =>
                {
                    b.Property<int>("JugadorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JugadorID"));

                    b.Property<int>("Asistencias")
                        .HasColumnType("int");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("int");

                    b.Property<decimal>("Sueldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("JugadorID");

                    b.HasIndex("EquipoID");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("_5544___Group_4_TALLER.Models.Partido", b =>
                {
                    b.Property<int>("PartidoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartidoID"));

                    b.Property<int>("Empatados")
                        .HasColumnType("int");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<int>("Ganados")
                        .HasColumnType("int");

                    b.Property<int>("Jugados")
                        .HasColumnType("int");

                    b.Property<int>("Perdidos")
                        .HasColumnType("int");

                    b.HasKey("PartidoID");

                    b.HasIndex("EquipoID");

                    b.ToTable("Partido");
                });

            modelBuilder.Entity("_5544___Group_4_TALLER.Models.TablaPosiciones", b =>
                {
                    b.Property<int>("TablaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TablaID"));

                    b.Property<int>("DiferenciaGol")
                        .HasColumnType("int");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("int");

                    b.Property<int>("PosicionActual")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("TablaID");

                    b.HasIndex("EquipoID")
                        .IsUnique();

                    b.ToTable("TablaPosiciones");
                });

            modelBuilder.Entity("_5544___Group_4_TALLER.Models.Jugador", b =>
                {
                    b.HasOne("_5544___Group_4_TALLER.Models.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("_5544___Group_4_TALLER.Models.Partido", b =>
                {
                    b.HasOne("_5544___Group_4_TALLER.Models.Equipo", "Equipo")
                        .WithMany("Partidos")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("_5544___Group_4_TALLER.Models.TablaPosiciones", b =>
                {
                    b.HasOne("_5544___Group_4_TALLER.Models.Equipo", "Equipo")
                        .WithOne("TablaPosiciones")
                        .HasForeignKey("_5544___Group_4_TALLER.Models.TablaPosiciones", "EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("_5544___Group_4_TALLER.Models.Equipo", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("Partidos");

                    b.Navigation("TablaPosiciones")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
